"""Generate the bundled synthetic test clip (developer tool; the result is committed, users never run this).

Needs: ``espeak-ng``, ``ffmpeg``, numpy, soundfile.  Everything is synthetic and created here, so there are no rights issues:
two espeak-ng voices read four English lines; a soft synthetic "music bed" and a short "effect" are mixed in; the video is a black
320x180 picture.  Output (``assets/test_clip``): ``voxprint-test-clip.mkv``, ``ref_voice.wav`` (clean 24 kHz reference of speaker B for
the TTS cloning test) and ``expected.json`` (ground truth: lines, speakers, times, reference text).

    python tools/make_test_clip.py
"""
from __future__ import annotations

import json
import subprocess
import tempfile
from pathlib import Path
from typing import Any, Dict

import numpy as np
import soundfile as sf

OUT = Path(__file__).resolve().parent.parent / "assets" / "test_clip"
SR = 44100
LINES = [
    ("A", "en-us+m3", "Good evening. I was hoping you would come tonight."),
    ("B", "en-us+f3", "I almost stayed home, but the rain stopped, so here I am."),
    ("A", "en-us+m3", "Then let us not waste the evening. Tell me everything."),
    ("B", "en-us+f3", "It is a long story, and it begins with a letter."),
]
GAP = 0.45            # seconds of silence between lines
LEAD = 0.8            # seconds of music before the first line


def speak(voice: str, text: str, wav: Path) -> np.ndarray:
    subprocess.run(["espeak-ng", "-v", voice, "-s", "150", "-p", "45", "-w", str(wav), text], check=True)
    data, sr = sf.read(str(wav), dtype="float32")
    if data.ndim > 1:
        data = data.mean(axis=1)
    # resample to 44.1 kHz with plain linear interpolation (good enough for a synthetic clip)
    n = int(len(data) * SR / sr)
    return np.interp(np.linspace(0, len(data) - 1, n), np.arange(len(data)), data).astype(np.float32)


def music_bed(seconds: float) -> np.ndarray:
    t = np.arange(int(seconds * SR)) / SR
    chords = [(220.0, 277.18, 329.63), (196.0, 246.94, 293.66), (174.61, 220.0, 261.63), (196.0, 246.94, 293.66)]
    out = np.zeros_like(t, dtype=np.float32)
    seg = max(1, int(len(t) / len(chords)))
    for i, ch in enumerate(chords):
        s, e = i * seg, len(t) if i == len(chords) - 1 else (i + 1) * seg
        for f in ch:
            out[s:e] += np.sin(2 * np.pi * f * t[s:e]) * 0.08
    fade = np.minimum(1.0, np.minimum(t, seconds - t) / 0.5).astype(np.float32)
    return out * fade


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    tmp = Path(tempfile.mkdtemp(prefix="vmd-clip-"))
    cursor = LEAD
    speech = np.zeros(int((LEAD + 40) * SR), dtype=np.float32)
    expected: Dict[str, Any] = {"language": "en", "sample_rate": SR, "lines": [],
                                 "note": "synthetic clip generated by tools/make_test_clip.py"}
    ref = None
    for i, (spk, voice, text) in enumerate(LINES):
        w = speak(voice, text, tmp / f"l{i}.wav")
        w = w / max(1e-6, float(np.abs(w).max())) * 0.7
        s = int(cursor * SR)
        speech[s:s + len(w)] += w
        expected["lines"].append({"speaker": spk, "start": round(cursor, 2), "end": round(cursor + len(w) / SR, 2), "text": text})
        if i == 1:
            ref = (w.copy(), text)
        cursor += len(w) / SR + GAP
    total = cursor + 0.6
    speech = speech[:int(total * SR)]
    bed = music_bed(total)
    # a short "door slam" effect (decaying noise) between the 2nd and 3rd line
    rng = np.random.default_rng(7)
    fx = np.zeros_like(speech)
    t0 = int((expected["lines"][1]["end"] + 0.1) * SR)
    n = int(0.25 * SR)
    fx[t0:t0 + n] = rng.standard_normal(n).astype(np.float32) * np.exp(-np.linspace(0, 9, n)).astype(np.float32) * 0.25
    mix = speech + bed + fx
    mix = (mix / max(1.0, float(np.abs(mix).max()) / 0.95)).astype(np.float32)
    stereo = np.stack([mix, mix * 0.98], axis=1)
    wav = tmp / "mix.wav"
    sf.write(str(wav), stereo, SR, subtype="PCM_16")
    clip = OUT / "voxprint-test-clip.mkv"
    subprocess.run(["ffmpeg", "-y", "-v", "error", "-f", "lavfi", "-i", f"color=c=black:s=320x180:r=10:d={total:.2f}", "-i", str(wav),
                    "-c:v", "libsvtav1", "-preset", "10", "-crf", "35", "-pix_fmt", "yuv420p", "-c:a", "flac", "-shortest",
                    "-metadata:s:a:0", "language=eng", str(clip)], check=True)
    assert ref is not None
    r24 = np.interp(np.linspace(0, len(ref[0]) - 1, int(len(ref[0]) * 24000 / SR)), np.arange(len(ref[0])), ref[0]).astype(np.float32)
    sf.write(str(OUT / "ref_voice.wav"), r24, 24000, subtype="PCM_16")
    expected["reference"] = {"file": "ref_voice.wav", "speaker": "B", "text": ref[1], "seconds": round(len(r24) / 24000, 2)}
    expected["duration"] = round(total, 2)
    (OUT / "expected.json").write_text(json.dumps(expected, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    (OUT / "README.txt").write_text(
        "Synthetic test clip for the Voxprint Movie Dubber diagnostics.\n"
        "Created by tools/make_test_clip.py: espeak-ng voices (GPL-3.0 program; its synthetic output is not covered by the GPL),\n"
        "a generated chord bed and a generated noise effect, black video. No third-party recordings. CC0 / public domain.\n", encoding="utf-8")
    print(clip, clip.stat().st_size, "bytes;", round(total, 1), "s")


if __name__ == "__main__":
    main()
